apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-vms-prd
  namespace: openshift-gitops
spec:
  destination:
    namespace: workshop-gitops-vms-prd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prd
    repoURL: git@github.com:anibalcoral/OpenShift-Virtualization-GitOps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true