---
    - name: Check if Apps repository exists
      ansible.builtin.stat:
        path: "{{ apps_repo_path }}"
      register: apps_repo

    - name: Fail if Apps repository not found
      ansible.builtin.fail:
        msg: |
          Apps repository not found at {{ apps_repo_path }}
          Please clone the Apps repository: git clone {{ apps_repo_url }} {{ apps_repo_path }}
      when: not apps_repo.stat.exists

    - name: Get cluster domain from OpenShift
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Ingress
        name: cluster
      register: cluster_ingress

    - name: Set cluster domain variable
      ansible.builtin.set_fact:
        cluster_domain: "{{ cluster_ingress.resources[0].spec.domain }}"

    - name: Display detected cluster domain
      ansible.builtin.debug:
        msg: "Detected cluster domain: {{ cluster_domain }}"

    - name: Switch to vms-dev branch and ensure it is up-to-date
      ansible.builtin.git:
        repo: "{{ apps_repo_url }}"
        dest: "{{ apps_repo_path }}"
        version: vms-dev
        update: true
      delegate_to: localhost

    - name: Extract current dev domain
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          grep -o "value: dev-workshop-gitops-vms\.[^\"]*" "{{ apps_repo_path }}/overlays/dev/kustomization.yaml" | sed 's/value: //' || echo ""
      register: current_dev_domain
      changed_when: false

    - name: Extract current hml domain
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          grep -o "value: hml-workshop-gitops-vms\.[^\"]*" "{{ apps_repo_path }}/overlays/hml/kustomization.yaml" | sed 's/value: //' || echo ""
      register: current_hml_domain
      changed_when: false

    - name: Extract current prd domain
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          grep -o "value: workshop-gitops-vms\.[^\"]*" "{{ apps_repo_path }}/overlays/prd/kustomization.yaml" | sed 's/value: //' || echo ""
      register: current_prd_domain
      changed_when: false

    - name: Set expected domain variables
      ansible.builtin.set_fact:
        expected_dev_domain: "dev-workshop-gitops-vms.{{ cluster_domain }}"
        expected_hml_domain: "hml-workshop-gitops-vms.{{ cluster_domain }}"
        expected_prd_domain: "workshop-gitops-vms.{{ cluster_domain }}"

    - name: Display current and expected domain configurations
      ansible.builtin.debug:
        msg:
          - "Current dev domain: {{ current_dev_domain.stdout }}"
          - "Expected dev domain: {{ expected_dev_domain }}"
          - "Current hml domain: {{ current_hml_domain.stdout }}"
          - "Expected hml domain: {{ expected_hml_domain }}"
          - "Current prd domain: {{ current_prd_domain.stdout }}"
          - "Expected prd domain: {{ expected_prd_domain }}"

    - name: Check if an update is needed
      ansible.builtin.set_fact:
        update_needed: >-
          {{
            (current_dev_domain.stdout != expected_dev_domain) or
            (current_hml_domain.stdout != expected_hml_domain) or
            (current_prd_domain.stdout != expected_prd_domain)
          }}

    - name: Update environment domains if necessary
      when: update_needed
      block:
        - name: Update dev environment domain
          ansible.builtin.replace:
            path: "{{ apps_repo_path }}/overlays/dev/kustomization.yaml"
            regexp: 'value: dev-workshop-gitops-vms\.[^"]*'
            replace: "value: {{ expected_dev_domain }}"

        - name: Update hml environment domain
          ansible.builtin.replace:
            path: "{{ apps_repo_path }}/overlays/hml/kustomization.yaml"
            regexp: 'value: hml-workshop-gitops-vms\.[^"]*'
            replace: "value: {{ expected_hml_domain }}"

        - name: Update prd environment domain
          ansible.builtin.replace:
            path: "{{ apps_repo_path }}/overlays/prd/kustomization.yaml"
            regexp: 'value: workshop-gitops-vms\.[^"]*'
            replace: "value: {{ expected_prd_domain }}"

    - name: Commit and push domain configuration changes
      when: update_needed and auto_commit
      block:
        - name: Commit domain configuration changes
          ansible.builtin.shell:
            cmd: |
              git add .
              git commit -m "feat: update cluster domain to {{ cluster_domain }}

              - Update development domain to: {{ expected_dev_domain }}
              - Update homologation domain to: {{ expected_hml_domain }}
              - Update production domain to: {{ expected_prd_domain }}"
          args:
            chdir: "{{ apps_repo_path }}"
          changed_when: true
          ignore_errors: true

        - name: Push changes to vms-dev branch
          ansible.builtin.shell:
            cmd: git push origin vms-dev
          args:
            chdir: "{{ apps_repo_path }}"
          ignore_errors: true

    - name: Merge and push changes through environment branches
      when: update_needed and auto_commit
      block:
        - name: Switch to vms-hml branch and merge from dev
          ansible.builtin.git:
            repo: "{{ apps_repo_url }}"
            dest: "{{ apps_repo_path }}"
            version: vms-hml
            update: yes
        - name: Merge vms-dev into vms-hml
          ansible.builtin.shell:
            cmd: git merge vms-dev
            chdir: "{{ apps_repo_path }}"
        - name: Push changes to vms-hml branch
          ansible.builtin.shell:
            cmd: git push origin vms-hml
            chdir: "{{ apps_repo_path }}"

        - name: Switch to main branch and merge from hml
          ansible.builtin.git:
            repo: "{{ apps_repo_url }}"
            dest: "{{ apps_repo_path }}"
            version: main
            update: yes
        - name: Merge vms-hml into main
          ansible.builtin.shell:
            cmd: git merge vms-hml
            chdir: "{{ apps_repo_path }}"
        - name: Push changes to main branch
          ansible.builtin.shell:
            cmd: git push origin main
            chdir: "{{ apps_repo_path }}"

        - name: Switch back to vms-dev branch
          ansible.builtin.git:
            repo: "{{ apps_repo_url }}"
            dest: "{{ apps_repo_path }}"
            version: vms-dev

    - name: Display final configuration and status
      ansible.builtin.debug:
        msg:
          - "{{ 'Domain configuration updated successfully!' if update_needed else 'Domain configuration is already correct.' }}"
          - "Development: https://{{ expected_dev_domain }}"
          - "Homologation: https://{{ expected_hml_domain }}"
          - "Production: https://{{ expected_prd_domain }}"