---
- name: Remove OpenShift GitOps Workshop Resources
  hosts: local
  gather_facts: false
  vars:
    workshop_namespace: "workshop-gitops-vms"

  tasks:
    - name: Remove ArgoCD Applications
      kubernetes.core.k8s:
        state: absent
        api_version: argoproj.io/v1alpha1
        kind: Application
        name: "{{ item }}"
        namespace: openshift-gitops
      loop:
        - workshop-vms-dev
        - workshop-vms-hml
        - workshop-vms-prd
      ignore_errors: true

    - name: Remove workshop namespaces
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop:
        - "{{ workshop_namespace }}-dev"
        - "{{ workshop_namespace }}-hml"
        - "{{ workshop_namespace }}-prd"
        - "{{ workshop_namespace }}"
      ignore_errors: true

    - name: Remove ArgoCD cluster role binding
      kubernetes.core.k8s:
        state: absent
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: argocd-workshop-admin
      ignore_errors: true

    - name: Remove ArgoCD repository secret
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Secret
        name: workshop-gitops-repo
        namespace: openshift-gitops
      ignore_errors: true

    - name: Remove OpenShift GitOps Operator (optional)
      kubernetes.core.k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: openshift-gitops-operator
        namespace: openshift-operators
      when: remove_operator | default(false) | bool

    - name: Display removal completion message
      debug:
        msg:
          - "Workshop resources have been removed."
          - "Removed: Applications, Namespaces, ClusterRoleBinding, Repository Secret"
          - "Note: OpenShift GitOps Operator was not removed by default."
          - "To remove the operator, run with: ansible-playbook ... -e remove_operator=true"