---
- name: Validate Cluster Domain
  hosts: local
  gather_facts: true
  vars:
    apps_repo_path: "/opt/OpenShift-Virtualization-GitOps-Apps"
    apps_repo_url: "https://github.com/anibalcoral/OpenShift-Virtualization-GitOps-Apps.git"
    skip_ssh_setup: false
    auto_commit: true

  tasks:
    - name: Validate Cluster Domain
      ansible.builtin.include_tasks: tasks/validate-cluster-domain-tasks.yaml
      when: not skip_ssh_setup
